// Generated by CoffeeScript 1.6.3
(function() {
  var addListener, modifierNames, pressedModifiers, resetModifiers, updateModifier;

  addListener = function(el, event, handler) {
    if (el.addEventListener != null) {
      el.addEventListener(event, handler, false);
    } else if (el.attachEvent != null) {
      el.attachEvent('on' + event, function() {
        return handler(window.event);
      });
    }
  };

  modifierNames = {
    '⇧': 16,
    shift: 16,
    '⌃': 17,
    ctrl: 17,
    control: 17,
    '⌥': 18,
    alt: 18,
    option: 18,
    '⌘': 91,
    command: 91
  };

  pressedModifiers = {};

  resetModifiers = function() {
    var k, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = modifierNames.length; _i < _len; _i++) {
      k = modifierNames[_i];
      _results.push(pressedModifiers[k] = false);
    }
    return _results;
  };

  updateModifier = function(e) {
    var k, key, val, _i, _len, _results;
    key = e.keyCode;
    val = e.type === 'keydown';
    if (key === 93 || key === 224) {
      key = 91;
    }
    _results = [];
    for (_i = 0, _len = modifierNames.length; _i < _len; _i++) {
      k = modifierNames[_i];
      _results.push(pressedModifiers = val);
    }
    return _results;
  };

  resetModifiers();

  addListener(document, 'keydown', updateModifier);

  addListener(document, 'keyup', updateModifier);

  addListener(window, 'focus', resetModifiers);

  this.modifiers = pressedModifiers;

}).call(this);
