// Generated by CoffeeScript 1.6.3
(function() {
  var modifierNames, pressedModifiers, resetModifiers, updateModifier;

  modifierNames = {
    shift: 16,
    control: 17,
    alt: 18,
    option: 18,
    command: 91
  };

  pressedModifiers = {};

  resetModifiers = function() {
    var k, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = modifierNames.length; _i < _len; _i++) {
      k = modifierNames[_i];
      _results.push(pressedModifiers[k] = false);
    }
    return _results;
  };

  updateModifier = function(e) {
    var k, key, val, _i, _len, _results;
    key = e.keyCode;
    val = e.type === 'keydown';
    if (key === 93 || key === 224) {
      key = 91;
    }
    _results = [];
    for (_i = 0, _len = modifierNames.length; _i < _len; _i++) {
      k = modifierNames[_i];
      _results.push(pressedModifiers = val);
    }
    return _results;
  };

  resetModifiers();

  document.addEventListener('keydown', updateModifier);

  window.addEventListener('focus', resetModifiers);

  this.modifiers = pressedModifiers;

}).call(this);
